name: 🐛 Bug Report
description: Signale un comportement inattendu ou un bug.
title: "[BUG] "
labels: [bug]
body:
  - type: textarea
    id: description
    attributes:
      label: Description du bug
      placeholder: Explique clairement le bug rencontré.
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Étapes pour reproduire
      placeholder: |
        1. Aller à '...'
        2. Cliquer sur '...'
        3. Voir l'erreur
    validations:
      required: true

  - type: input
    id: browser
    attributes:
      label: Navigateur ou terminal utilisé
      placeholder: ex. Chrome 125, Safari, curl
